stages:
- build

variables:
    FACTORY_PRODUCT_NAME: qgis-arm
    FACTORY_PACKAGE_TYPE: debpkg

.arm-build:
  stage: build
  script:
     - make $BUILDNAME-build
  environment:
    name: snap
  tags:
    - infrav3

build:arm32:
  extends: .arm-build
  variables:
    BUILDNAME: arm32
    FACTORY_PACKAGE_NAME: qgis-arm32
  when: manual

build:arm64:
  extends: .arm-build
  variables:
    BUILDNAME: arm64
    FACTORY_PACKAGE_NAME: qgis-arm64
  when: manual

build:rpi3:
  extends: .arm-build
  variables:
    BUILDNAME: rpi3
    FACTORY_PACKAGE_NAME: qgis-rpi3
  when: manual

